### ISSUE TITLE
"zsh: command not found: liara" error after installing @liara/cli using npm install -g command

### ISSUE THREAD

**Issue by Matin-B** [liara-cloud/liara-cli#108]
I have installed the @liara/cli using the npm install -g @liara/cli command in my terminal. However, when I try to run the "liara" command in my terminal, it returns an error message that reads "zsh: command not found: liara".

I have tried uninstalling and reinstalling @liara/cli multiple times, but the issue persists. I have also tried restarting my terminal and my computer, but the error message still appears.

Can anyone please help me resolve this issue? I would appreciate any suggestions or insights on how to fix this problem.

Environment:
- Operating System: Manjaro Linux 22.1.0
- Node.js version: v19.8.1
- npm version: 8.19.2
- @liara/cli version: @liara/cli@3.4.0

**Comment by vashian** [comment]
You can use the **`npm bin`** command to check where the binary for the package was installed. Run **`npm bin`** in your terminal and it will output the path to the bin directory of the current package.

Once you know where the package was installed, you can add the directory to your system's **PATH** environment variable. You can do this by adding the following line to your shell's startup file `(~/.zshrc)`:

```zsh
export PATH="/path/to/package/bin:$PATH"
```

At the end, source your shell's startup file so that the changes take effect. Run the following command to do this:

 ```zsh
source ~/.zshrc
```


Also, you can try using **sudo** to install the package as the superuser.

```zsh
sudo npm i -g @liara/cli
```

**Comment by Matin-B** [comment]
> You can use the **`npm bin`** command to check where the binary for the package was installed. Run **`npm bin`** in your terminal and it will output the path to the bin directory of the current package.
> 
> Once you know where the package was installed, you can add the directory to your system's **PATH** environment variable. You can do this by adding the following line to your shell's startup file `(~/.zshrc)`:
> 
> ```shell
> export PATH="/path/to/package/bin:$PATH"
> ```
> 
> At the end, source your shell's startup file so that the changes take effect. Run the following command to do this:
> 
> ```shell
> source ~/.zshrc
> ```
> 
> Also, you can try using **sudo** to install the package as the superuser.
> 
> ```shell
> sudo npm i -g @liara/cli
> ```

Thanks

**Comment by vashian** [comment]
> > You can use the **`npm bin`** command to check where the binary for the package was installed. Run **`npm bin`** in your terminal and it will output the path to the bin directory of the current package.
> > Once you know where the package was installed, you can add the directory to your system's **PATH** environment variable. You can do this by adding the following line to your shell's startup file `(~/.zshrc)`:
> > ```shell
> > export PATH="/path/to/package/bin:$PATH"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > At the end, source your shell's startup file so that the changes take effect. Run the following command to do this:
> > ```shell
> > source ~/.zshrc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, you can try using **sudo** to install the package as the superuser.
> > ```shell
> > sudo npm i -g @liara/cli
> > ```
> 
> Thanks

If everything is working properly, feel free to go ahead and close the issue.

**Comment by Matin-B** [comment]
> > > You can use the **`npm bin`** command to check where the binary for the package was installed. Run **`npm bin`** in your terminal and it will output the path to the bin directory of the current package.
> > > Once you know where the package was installed, you can add the directory to your system's **PATH** environment variable. You can do this by adding the following line to your shell's startup file `(~/.zshrc)`:
> > > ```shell
> > > export PATH="/path/to/package/bin:$PATH"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > At the end, source your shell's startup file so that the changes take effect. Run the following command to do this:
> > > ```shell
> > > source ~/.zshrc
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, you can try using **sudo** to install the package as the superuser.
> > > ```shell
> > > sudo npm i -g @liara/cli
> > > ```
> > 
> > 
> > Thanks
> 
> If everything is working properly, feel free to go ahead and close the issue.

Sure.
