### ISSUE TITLE
Multi-Account Login

### ISSUE THREAD

**Issue by seantheyahn** [liara-cloud/liara-cli#16]
It is good to be able to have multiple-account access (e.g. for freelancers), 
you could add something like this in constants.ts for relative path lookup:

```
import fs from 'fs'

//...

if (fs.existsSync('.liara.json')) {
    export const GLOBAL_CONF_PATH = path.resolve('.liara.json')
} else {
    export const GLOBAL_CONF_PATH = path.join(os.homedir(), '.liara.json')
}
```

**Comment by mhemrg** [comment]
Thanks for the idea.
I guess we need to add `.liara.json` to the default ignore list to prevent uploading it.
PRs are welcome.
