### ISSUE TITLE
v2.7.0 win32-x64 Not usable: SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by ImanNavidi** [liara-cloud/liara-cli#19]
Hi
After installation using "npm install -g @liara/cli" on windows 10x64, all commands (except -v and help) show the following error:
"SyntaxError: Unexpected token *"

**Comment by mhemrg** [comment]
Hi,
What is your NodeJS version? Use `node -v` to check it out.
We recommend using Node >= 10.

**Comment by ImanNavidi** [comment]
It was 8,
Upgrading to the latest version (14) solved the problem
