### ISSUE TITLE
Run in development mode

### ISSUE THREAD

**Issue by mhemrg** [liara-cloud/liara-cli#55]
Sounds like after upgrading oclif to the latest version, we've missed a part.
https://github.com/oclif/core/blob/main/MIGRATION.md#update-your-bin-scirpts

We should be able to run the cli using `./bin/dev` file in development mode.

**Comment by mhemrg** [comment]
@vashian Can you please take a look at?

**Comment by vashian** [comment]
@mhemrg I've been searching for how we can make its performance better.
That was weird to me cause nobody never ever mentions this anywhere.


Reading `tsconfig.json` at line number 6 we'd specify `outDir` and it takes much time to build the whole package and put it at `/lib/
After I commented this line `/bin/dev` works well.

**Comment by vashian** [comment]
@mhemrg If you think it's ok I'll make PR and add a new `dev` script.

**Comment by mhemrg** [comment]
If we comment out the `outDir` field, then what happens to our production build? After all, we need to run `npm run prepack` and we need to have the `lib/` directory.
