### ISSUE TITLE
search: can we run liara autocomplete automaticly on first initialization?

### ISSUE THREAD

**Issue by userdehghani** [liara-cloud/liara-cli#89]

**Comment by vashian** [comment]
@userdehghani It is not possible in oclif, however, the Heroku CLI does this ([the data needed for completions is behind an API](https://blog.heroku.com/completing-autocomplete)).
could not find any related topic about dynamic autocomplete in oclif CLI.

feel free to reopen this issue if you find any solutions, thanks ❤️
